name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  test:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET SDK v5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Run tests
        run: |
          git clone https://github.com/dotnet/orleans
          .\perftests\RunPerformanceTests.ps1 -nugetClientFilePath .\dev-b58613fbc338b8e142d29b3bdb74e92a83a259fb\NuGet.exe -solutionFilePath .\orleans\Orleans.sln -resultsFilePath "result-$((Get-Date).ToString('MM-dd-yyyyhh-mm-ss')).csv" -skipCleanRestores -skipColdRestores -skipForceRestores
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: .\perftests\*.csv