name: benchmark_nuget_windows

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  ITERATION_COUNT: 10
  BASE_VERSION: dev-b58613fbc338b8e142d29b3bdb74e92a83a259fb
  BRANCH_VERSION1: caching-touch-metadata
  BRANCH_VERSION2: caching-touch-metadata3
  BRANCH_VERSION3: caching-touch-metadata-restorerunner
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  benchmark_nuget_windows:
    runs-on: windows-2019
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout test solutions
        run: |
          git clone --recursive https://github.com/dotnet/orleans

      - name: Disable strong name verification
        run: |
          reg DELETE "HKLM\Software\Microsoft\StrongName\Verification" /f
          reg ADD "HKLM\Software\Microsoft\StrongName\Verification\*,*" /f
          reg DELETE "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification" /f
          reg ADD "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification\*,*" /f

      - name: Benchmark
        shell: pwsh
        run: |
          $solutions = @("orleans")
          $versions = @("${{env.BASE_VERSION}}", "${{env.BRANCH_VERSION1}}", "${{env.BRANCH_VERSION2}}", "${{env.BRANCH_VERSION3}}")
          For ($i=0; $i -lt 2; $i++) {
              ForEach ($solution In $solutions) {
                  ForEach ($version In $versions) {
                    .\scripts\perftests\RunPerformanceTests.ps1 -nugetClientFilePath .\artifacts\$version\NuGet.exe -solutionFilePath $solution -resultsFilePath results.csv -iterationCount ${{env.ITERATION_COUNT}}
                    Add-Content -Path .\results.csv -Value $version
                    Add-Content -Path .\results.csv -Value ""
                  }
              }
          }

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: results_windows_nuget
          path: results.csv